package com.mustk.newsapp.shared

object Constant {
    const val SHARED_PREFS_NAME = "app_preferences"
    const val NOTIFICATIONS_ENABLED = "notifications_enabled"
    const val DARK_THEME_ENABLED = "dark_theme_enabled"
    const val LANGUAGE_ITEM = "language_item"
    const val SEND_MESSAGE_EMAIL = "mustkmber@gmail.com"
    const val NULL_PATH_IMAGE = "https://i.ibb.co/8m7z4x0/poster.jpg"
    const val APP_URL = "https://github.com/mustafakamber/NewsApp"
    const val ABOUT_ME_URL = "https://github.com/mustafakamber"
    const val APIKEY_QUERY_PARAM = "api_token"
    const val LANGUAGE_QUERY_PARAM = "language"
    const val ALL_QUERY_PARAM = "all"
    const val UUID_QUERY_PARAM = "uuid/"
    const val SEARCH_QUERY_PARAM = "search"
    const val CATEGORIES_QUERY_PARAM = "categories"
    const val LANGUAGE_EN = "en"
    const val LANGUAGE_TR = "tr"
    const val LANGUAGE_FR = "fr"
    const val LANGUAGE_ES = "es"
    const val LANGUAGE_IT = "it"
    const val LANGUAGE_DE = "de"
    const val LANGUAGE_AR = "ar"
    const val BASE_URL = "https://api.thenewsapi.com/v1/news/"
    const val USERS_COLLECTION = "Users"
    const val NEWS_COLLECTION = "News"
    const val UUID_FIELD = "uuid"
    const val USER_FIELD = "user"
    const val TITLE_FIELD = "title"
    const val DESCRIPTION_FIELD = "description"
    const val PHOTO_FIELD = "photo"
    const val IMAGE_URL_FIELD = "image_url"
    const val NEWS_URL_FIELD = "url"
    const val PUBLISHED_AT_FIELD = "published_at"
    const val SOURCE_FIELD = "source"
    const val CATEGORIES_FIELD = "categories"
    const val SNIPPET_FIELD = "snippet"
    const val EMAIL_FIELD = "email"
    const val META_FIELD = "meta"
    const val DATA_FIELD = "data"
    const val ERROR_FIELD = "error"
    const val CODE_FIELD = "code"
    const val MESSAGE_FIELD = "message"
    const val FOUND_FIELD = "found"
    const val LANGUAGE_FIELD = "language"
    const val RETURNED_FIELD = "returned"
    const val LIMIT_FIELD = "limit"
    const val PAGE_FIELD = "page"
    const val NULL_JSON = "Empty Json File"
    const val CATEGORY_GENERAL = "general"
    const val CATEGORY_POLITIC = "politics"
    const val CATEGORY_SPORT = "sports"
    const val CATEGORY_TECH = "tech"
    const val CATEGORY_BUSINESS = "business"
    const val CATEGORY_ENTERTAINMENT = "entertainment"
    const val CATEGORY_SCIENCE = "science"
    const val PASSWORD_LIMIT = 12
    const val SHARE_SCREEN_TITLE = "Share"
    const val SHARE_SCREEN_TYPE = "text/plain"
    const val TIME_OUT_MILLIS = 500L
    const val SEARCH_THRESHOLD_LENGTH = 2
    const val DATE_BRACKET = "-"
    const val NULL_PHOTO = " "
    const val CATEGORY_BRACKET = ", "
    const val CHANNEL_ID = "channel_id"
    const val NOTIFICATION_NAME = "NewsNotification"
    const val NOTIFICATION_REQUEST_CODE = 1001
    const val PENDING_INTENT_REQUEST_CODE = 0
    const val SQLITE_DATABASE_NAME = "NewsDB"
    const val PUBLISHED_AT_DATE_MIN = 0
    const val PUBLISHED_AT_DATE_MAX = 10
    const val PUBLISHED_AT_TIME_MIN = 11
    const val PUBLISHED_AT_TIME_MAX = 16
    const val SHORT_TITLE_MAX_SIZE = 65
    const val SHORT_SOURCE_MAX_SIZE = 13
    const val NOTIFICATION_HOUR = 10
    const val NOTIFICATION_MINUTE = 30
    const val NOTIFICATION_SECOND = 0
    const val NOTIFICATION_NEXT_DAY = 1
    const val HEADLINE_SIZE = 3
    const val CATEGORY_CONVERT_CHAR = ","
    const val DATABASE_VERSION = 5
    const val TITLE_FIRST_WORD_CHAR = " "
    const val INTER_TEST = "ca-app-pub-3940256099942544/1033173712"
}